### ISSUE TITLE
Activity.activityEntityId

### ISSUE THREAD

**Issue by cbizon** [clingen-data-model/interpretation#11]
I don't know what this attribute is...  any takers?

**Comment by bpow** [comment]
I inferred that it is analogous to `Data.evidenceTypeId`. Both `Data` and `Activity` have subtypes, and this field specifies the subtype for the item in that row.

**Comment by cbizon** [comment]
So is this something that is used in building the spreadsheet/data but which would not make it through into the final model / JSON?

**Comment by cbizon** [comment]
Tabling this until we decide what to do about Activity

**Comment by larrybabb** [comment]
The activity.id in the spreadsheet is the "abstract" id for any of the Activity subclasses.  

I believe we are now at a point with the SEPIO harmonization that the "Activity" concept is no longer needed (except for a conceptual model).  

If we choose to leave Activity in then "id" should stay, since it (like the other Activity attributes) are inherited by the AssessCriterion, GenerateInterprtation and CaptureData subclasses.

**Comment by cbizon** [comment]
I mostly agree about getting rid of Activity overall, but the most recent of Matt's pictures that I saw still included the CaptureData activity.  Maybe we should discuss on the call.

**Comment by bpow** [comment]
Echoing @cbizon , the SEPIO model still allows for representation of a `Process`, and as we've discussed on the most recent calls, we could make accessory links to the process so that SEPIO could go through an assertion-to-evidenceline path without interrupting activities, but there could also be a different path through the same data that would more closely reflect PROV.

As to the question of this issue, the (renamed) `activityTypeId` in the `Activity` sheet references the class/inheritance structure from `Type`. Until/if we remove `Activity` and subtypes, it will need to remain there. I'm all for closing this issue. Happy to re-discuss if someone wants to re-open.
