### ISSUE TITLE
Change AggregationSegregationData to AggregateSegregationData

### ISSUE THREAD

**Issue by cbizon** [clingen-data-model/interpretation#14]
Can somebody let me know if it's ok to just change this name in Types or do I have to make changes elsewhere as well?

**Comment by cbizon** [comment]
Also, if people disagree with the change, speak up

**Comment by larrybabb** [comment]
If you change the "type" (frmrly "entity") name then you should really change the prefix code value to stay in sync.  If you do that then it will cause the generation of the ids on other pages to be different which is ok, but the foreign key values that are located in places like DataAttributes and others will need to be changed because they are static values.  It's a bit of a pain, but I think it is important for readability/clarity.

**Comment by bpow** [comment]
For this particular case, there is nothing else in the sheets doc you would need to change (the short form `AggSegData` would still be the same, so @larrybabb's point is true in general but not a problem in this case.

You would need to change some things in the middleman repo to match (e.g. `source/tech/model/entities/evidence/aggregation_segregation_data.md`)

:+1: from me on the name change.

**Comment by cbizon** [comment]
Thanks guys, I will make the change
