### ISSUE TITLE
AlleleFrequency (Group v Population)?

### ISSUE THREAD

**Issue by larrybabb** [clingen-data-model/interpretation#21]
Can we do a quick review of Group v Population Allele Frequency types to make sure they are correct?

And, can we discuss whether we can pull out a common substructure for them to share? Or possibly merge them to create a single type that can be used in either scenarios?

PopAllFreq has the following attributes
a. contextualAllele
b. population
c. ascertainment
**d. alleleFrequency**
e. alleleCount
f. alleleNumber
**g. hemizygousAlleleIndividualCount**
h. homozygousAlleleIndividualCount
**i. medianCoverage**

Whereas, GroupAllFreq has
a. contextualAllele
b. population
c. ascertainment
e. alleleCount
f. alleleNumber
**j. individualCount**
h. homozygousAlleleIndividualCount
**k. heterozygousAlleleIndividualCount**

**Comment by cbizon** [comment]
So we actually have this modeled as PopulationAlleleFrequency is a subclass of GroupAlleleFrequency.   PAF should therefore have all the attributes that group has.    For some reason, most of the attributes haven't been fixed to reflect that.

But anyway, I guess the question is whether we should go further and just merge them.  I think we should, and the attributes are the union of what's there.   I would call it AlleleFrequency.

**Comment by bpow** [comment]
:+1: for joining the two together-- a population is just one type of a group (albeit a rather large one).

Not sure how to best handle alleleFrequency vs. the combination alleleCount&alleleNumber: for a given data point, if we allow both to be present, then we have the potential for inconsistent data. The latter is nice to have because it lets you know something about precision (a small sample would have higher variablility), but I'm sure there are cases where only alleleFrequency is reported without the denominator.

**Comment by cbizon** [comment]
I think just leave them all.  Yes, possibility for inconsistent data, but we can at least document what the relationship ought to be.

**Comment by larrybabb** [comment]
agreed.
