### ISSUE TITLE
AlleleFrequency.ascertainment - code or not? 

### ISSUE THREAD

**Issue by larrybabb** [clingen-data-model/interpretation#23]
We have the "ascertainment" attribute listed as a code. If so, can we propose some values for the list and determine if it should be "customizable"?

**Comment by cbizon** [comment]
So our Frequency object can be used to calculate a frequency over a few different groups:

It might be a population sample
It might be cases from a database or some other source
It might be (age and ancestry matched?) controls

If we just want this broad level, we can probably make up codes for these cases.  If we leave it a string, we can allow more detailed info.  But since we already have the explanation attribute, I think it makes sense to codify it.  I don't see any external terms.

**Comment by larrybabb** [comment]
Code it is. We will allow it to be flexible and permit the use of custom codes.
