### ISSUE TITLE
Page index

### ISSUE THREAD

**Issue by cbizon** [clingen-data-model/interpretation#4]
The index on the left hand side of the page is using page.data.title to fill in the names.   But we had decided that the title attribute should not be set for all of the entities defined in the spreadsheet.  For those, the code that builds the links should be going to the data based on the Id in the page.

**Comment by larrybabb** [comment]
i left the reference to page.data.title because of some code in the layout.erb template file which I could not figure out how to get access to the id-based values.  It was sort of a cart and horse issue. If you can remove the duplication of data by removing the "title" attribute from the pages, please do.

**Comment by cbizon** [comment]
It seems as though if you can get the current-page.data.title, you should be able to get current_page.data.id and use that to go into the flattened data to get the name?  I took a quick look yesterday, but I didn't understand the layout code very well.

**Comment by cbizon** [comment]
Fixed. Now, if there is an id in the page, the word in the link is going to be the name from the json.
