### ISSUE TITLE
Splicing Prediction Data Structure?

### ISSUE THREAD

**Issue by larrybabb** [clingen-data-model/interpretation#41]
@cbizon 
I think we may need a "Splicing Prediction" data structure for example PS1.2 in the https://docs.google.com/document/d/1C7XDX0T5oB2TO3R4vy1wFuJCq0v-R66YKjZi3hiNbQU/edit#heading=h.qhaztvfaqsey doc.

Can we use the InSilicoPrediction type already defined?  Or is this something different.

**Comment by cbizon** [comment]
2 Issues, which are seperate.:
1) How do we structure splicing predictions?
2) Do we need splicing predictions for example PS1.2?

1) This would be done with InSilicoPrediction, type="splicing".
     It looks like for these predictions, you get a prediction for the wild type and the variant.  So if we wanted the NNSplice data from the example, we'd have 3 contextual alleles.  Say CA1 is the WT, then CA2 is G>C and CA3 is G>A.
`InSilicoPrediction
{
  ContextualAllele: CA1,
  type: "splicing"
  tool: "NNSplice"
  value: 0.9959
}
InSilicoPrediction
{
 ContextualAllele: CA2,
 type:"splicing",
 tool: "NNSplice",
 value: "0.918158"
}

InSilicoPrediction
{
 ContextualAlelle: CA3,
 type: "splicing",
 tool: "NNSplice",
 value: "0.908774"
}
`

2) Whether we need the data broken out as in the above for the example that we have or not.  On the one hand, I think it would make sense, if only just to show how to code it.  But the example is a little confusing.   We're using the rule that says if you are evaluating variant 1, and it has the same AA change as variant 2 and variant 2 is pathogenic, then variant 1 is more likely to be pathogenic.    But the idea of this example is that this rule isn't really applicable because variant 2 is thought to be pathogenic for a reason other than the AA change, namely that it affects splicing (pre-translation to amino acids).    What's shown though is splicing prediction for both variant 1 and variant 2, which (I think) shows that neither variant really is predicted to affect splicing.   

So when I coded this one up, I didn't really see those predictions as affecting the conclusion, and I left them out.  The relevant information (that variant 2 affects splicing) isn't really presented.   That said, if we think it's useful to code them up, it's straightforward to do as listed above.

**Comment by rrfreimuth** [comment]
This is an interesting example.  A few random comments (which are the only type I know how to make):

- The mock up that @cbizon produced above is very helpful.  It made me realize that the data being captured at that level isn't a splicing prediction, it is a splicing score.  That score is then interpreted (based on each algorithm's rules) to form a prediction as to whether or not a functional splice site exists at that location.

- The comparison of two splice scores (e.g., CA1 vs. CA2 or CA2 vs. CA3) is another layer of interpretation... does CA3 impact splicing as much as CA2?  (I'm not sure if this is useful, but it illustrates another layer that might need to be considered separately)

Given the above, I think it is useful to be able to express splicing scores/predictions as structured data.

The larger question of how this relates to the example in PS1.2 is not answered by my ramblings above.  As it turns out, I think it they are irrelevant for this question.

PS1 is "Same amino acid change as a previously established pathogenic variant regardless of nucleotide change".  It seems that implicit within that wording is the assumption that the pathogenicity is due to the amino acid change.  In the case of a splicing issue, this is not the case.  I think there are two ways to think about the wording of PS1:

PS1A:  Nucleotide change predicted to result in the same amino acid change as another (different) nucleotide change that was previously established to be pathogenic due to the change in amino acid

PS1B:  Nucleotide change predicted to result in the same functional change as another (different) nucleotide change that was previously established to be pathogenic due to the functional change

The first is likely the one that was intended by ACMG.  The second is written more generally and could include variants that impact other types of functional changes.  Neither are worded particularly well.

The point is that in example PS1.2, PS1A would not be met (because of the clause "pathogenic due to the change in amino acid") for CA3.  PS1B may or may not be met depending on the assessment of CA2 (because "functional change" means splicing in this case).

I realize that we cannot change the wording of the criteria, but we can use cases like this to highlight gaps that aren't covered or ambiguities in the current wording.  IMO, our model should separate the data being evaluated from the criteria so that when the latter changes the model doesn't break.

Feel free to push back if you disagree.

**Comment by larrybabb** [comment]
All good points above. In the spirit of expediency I think we should defer this and get out what we have. If it becomes important in practice we can relatively easily refactor this in.

**Comment by rrfreimuth** [comment]
No argument there.  I think we should bring this to Heidi, though, so she is aware of this sort of thing when she works with ACMG to update the criteria.
