### ISSUE TITLE
remove Data.wasGeneratedByActivityId (makes more sense as Entity.wasGeneratedBy)

### ISSUE THREAD

**Issue by bpow** [clingen-data-model/interpretation#5]
Similar to #3, `Data` inherits from `Entity`, which represents a W3C-Prov entity, so I think wasGeneratedByActivityId is redundant.

**Comment by cbizon** [comment]
Agreed -remove it

**Comment by larrybabb** [comment]
My only concern is that the "Entity" entity in the spreadsheet does not necessarily align 1-to-1 with the Provenance entity.  In theory yes, but in the spreadsheet, I assumed that any "used" item could be an Entity. Since there are many used items that are not generated by Activities in the scope of our model, I was thinking we'd try to control the specific kinds of entities that had this association.  For example, do we really want Critertion, Condition, Gene, CanonicalAllele, etc.. to have a "wasGeneratedBy" association in the documentation?  
Some of these may need special handling from a page generation template standpoint anyway in order to show references to our variant/allele model.
I'm fine with it for now, but I think we should keep an eye on how this evolves.

**Comment by bpow** [comment]
As long as wasGeneratedBy is of cardinality 0..1 or 0..*, I don't see any reason not to allow those other Entities to have a wasGeneratedBy field. For instance, CanonicalAlleles are generated somehow.

In the converse, I would be opposed to using the term "Entity" for something that does not actually map to the W3C-prov Entity because of the confusion that may cause. It would be even more confusing if some cg:entity subtypes satisfied criteria for being a prov:entity but not others.

**Comment by larrybabb** [comment]
technically speaking "everything" is an entity.  I'm not sure how we discern what W3C's prov model considers an entity.  Activities and Agents are entities...they get generated somehow.

We do have the ability to control this though (which is our fallback) for now we proceed as you have it.  And if we want to constraint those "entities" that are "used" but not generated from those that are generated, we should be able to add something or tweak something to get the result we want.

I would go with the direction you are on.

**Comment by tnavatar** [comment]
> On Nov 4, 2016, at 9:45 AM, Larry Babb <notifications@github.com> wrote:
> 
> technically speaking "everything" is an entity. I'm not sure how we discern what W3C's prov model considers an entity. Activities and Agents are entities...they get generated somehow.

I don’t think this is true (at least it isn’t in prov-o). They’re generated, yes, but they don’t have their own provenance attached to them (I suppose you could attach provenance to an Agent, but at some point, mom and dad are simpler terms, also modeling that activity is [probably] out of scope for ClinGen)

An Entity is anything you’re attaching provenance to. I think we did construct the Allele model to allow provenance to be attached, so an allele should be considered an entity. That said, I’m not sure we thought carefully about how we would use provenance in that context.

**Comment by bpow** [comment]
Accepted by acclamation on conference call.

Discussion also included the potential confusion of the W3C-PROV `Entity` vs. the more generic use of the word "entity" in terms of entity-attribute-value representation of data. The type `Entity` used in the interpretation model is intended to fulfill the contract of a W3C-PROV `Entity`
